version: "3.9"

services:
  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./fastapi:/app
      - /app/node_modules
    depends_on:
      - postgres

  nextjs:
    build: ./nextjs
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    depends_on:
      - fastapi

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data: